# Generated by Django 6.0.3 on 2026-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Gt2Jze5dpfYma2iM6qRaVGTadc0quqkr', editable=False, max_length=32, unique=True),
        ),
    ]
